"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['src/MQTTBuzz.py']
DATA_FILES = ['src/config.json','src/help.txt']
OPTIONS = {
    'iconfile': 'src/MQTTBuzz.icns',
    'includes': ['rumps', 'paho.mqtt.client', 'threading', 'json', 'os', 'time']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
